schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          title: VPC CIDR
          type: string
          description: "The CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        subnet_one_cidr:
          title: Subnet 1 CIDR
          type: string
          description: "The CIDR range for subnet one"
          default: 10.0.0.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))

